# Generated by Django 3.2.5 on 2021-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='記事Id')),
                ('hatena_entry_id', models.BigIntegerField(unique=True, verbose_name='はてな記事Id')),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='カテゴリ')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='タイトル')),
                ('summary', models.CharField(blank=True, default='', max_length=1000, null=True,
                                             verbose_name='サムネイル文')),
                ('content_md', models.TextField(blank=True, default='', null=True, verbose_name='内容_MarkDown')),
                ('content_html', models.TextField(blank=True, default='', null=True, verbose_name='内容_HTML')),
                ('draft', models.CharField(blank=True, choices=[('yes', '下書き'), ('no', '公開')],
                                           default='yes', max_length=10, null=True, verbose_name='下書き区分')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='削除日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'entry',
                'verbose_name': '記事',
                'verbose_name_plural': '記事'
            },
        ),
    ]
